import { ThemeProvider } from "@mui/material/styles";
import { AppProps } from "next/app";
import Head from "next/head";

import Snackbar from "@/components/parts/Snackbar";
import Layout from "@/components/templates/Layout";
import { swrConfig } from "@/lib/swr";
import theme from "@/lib/theme";
import { store } from "@/store/store";
import CssBaseline from "@mui/material/CssBaseline";
import { AdapterDateFns } from "@mui/x-date-pickers/AdapterDateFns";
import { LocalizationProvider } from "@mui/x-date-pickers/LocalizationProvider";
import { Session } from "next-auth";
import { SessionProvider } from "next-auth/react";
import { Provider } from "react-redux";
import { SWRConfig } from "swr";

import "@react-pdf-viewer/core/lib/styles/index.css";
import "@uploadthing/react/styles.css";

function App({
  Component,
  pageProps,
  session,
}: AppProps & { session: Session }) {
  return (
    <Provider store={store}>
      <Head>
        <title>BBCS Data Systems</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>

      <ThemeProvider theme={theme}>
        <LocalizationProvider dateAdapter={AdapterDateFns}>
          <CssBaseline />
          <SWRConfig value={swrConfig}>
            <SessionProvider session={session}>
              <Layout>
                <Component {...pageProps} />
              </Layout>
            </SessionProvider>
          </SWRConfig>

          <Snackbar />
        </LocalizationProvider>
      </ThemeProvider>
    </Provider>
  );
}

export default App;

// This is a little hacky solution to prevent `const { page } = router.query` is undefined on first rendering.
// https://nextjs.org/docs/messages/empty-object-getInitialProps
// https://github.com/vercel/next.js/discussions/11484
App.getInitialProps = async () => ({});
